on:
  push:
    branches:
      - main

jobs:
  basics:
    name: basic test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: List repo contents
        run: |
          pwd
          ls -lah
          
