on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  basics:
    name: basic test
    runs-on: ubuntu-latest
  
    steps:
      - name: MainEchoDefault
        run: echo "PR 2"
